server:
  port: 20200

spring:
  application:
    name: life-gateway
  cloud:
    gateway:
      routes:
      - id: life-weather
        uri: lb://life-weather
        predicates:
        - Path=/weather/**
        filters:
        - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:20000/eureka/

