server:
  port: 20300

spring:
  application:
    name: life-user
  datasource:
    username: root
    password: PANGzi!@#
    url: jdbc:mysql://mysql:3306/life
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:20000/eureka/